CREATE TABLE IF NOT EXISTS room (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code CHARACTER(5) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS sighting (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    roomId INTEGER,
    date TIMESTAMP NOT NULL,
    counter VARCHAR(64) NOT NULL,
    count INTEGER NOT NULL,
    FOREIGN KEY (roomId) REFERENCES room(id)
);
